upstream:
  url: "https://github.com/spack/spack-packages.git"
  base_branch: "develop"

output_repo:
  url: "https://github.com"
  push_branch: "integration-result"

patches:
  - name: "lxde-lxterminal"
    origin_name: "old_local_rcm_clone"
    # origin_url omitted: autofilled from the first 'updates' entry above
    branch: "packages/lxde-lxterminal_rebased"
  - name: "lxde-gpicview"
    origin_name: "old_local_rcm_clone"
    branch: "packages/lxde-gpicview_rebased"
  - name: "packages/fix_out_of_prefix_xfontsel_xedit"
    origin_name: "old_local_rcm_clone"
    origin_url: "/home/lcalori0/spack/old/spack_env_clones/scripts/clones/rcm_021_dev.clone"
    branch: "packages/fix_out_of_prefix_xfontsel_xedit_rebased"
    restructured: true
    filter_path: "var/spack/repos/builtin/packages/"
    filter_path_rename: "var/spack/repos/builtin/packages/:repos/spack_repo/builtin/packages/"

